-- FINAL DATABASE SETUP SCRIPT
-- Run this script in Supabase SQL Editor to setup the entire database structure.

-- 1. Enable RLS
alter table if exists "public"."ho_so" enable row level security;
alter table if exists "public"."don_hang" enable row level security;
alter table if exists "public"."yeu_cau_tu_van" enable row level security;
alter table if exists "public"."candidate_order" enable row level security;

-- 2. Create Profiles Table (Hồ sơ)
CREATE TABLE IF NOT EXISTS public.ho_so (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  ho_ten text not null,
  so_dien_thoai text,
  nam_sinh date,
  gioi_tinh text,
  que_quan text,
  nganh_nghe_mong_muon text,
  kinh_nghiem text,
  trinh_do_van_hoa text,
  tieng_nhat text,
  ghi_chu text,
  trang_thai text default 'Chờ tư vấn', -- 'Chờ tư vấn', 'Đợi đơn', 'Đỗ đơn', 'Rút đơn'
  nguon text default 'Web',
  anh_ho_so text,
  hon_nhan text,
  chieu_cao integer,
  can_nang integer,
  hut_thuoc text,
  thi_luc text,
  tay_thuan text,
  so_thich text
);

-- 3. Create Orders Table (Đơn hàng)
CREATE TABLE IF NOT EXISTS public.don_hang (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  ten_don_hang text not null,
  nganh_nghe text,
  dia_chi_lam_viec text,
  luong_co_ban text,
  so_luong_tuyen integer default 1,
  yeu_cau_khac text,
  trang_thai text default 'Đang tuyển',
  thoi_han_nop_ho_so date,
  mo_ta_cong_viec text,
  doi_tac text,
  nghiep_doan text,
  phi_don_hang text,
  ghi_chu text
);

-- 4. Create Consultation Requests Table (Yêu cầu tư vấn)
CREATE TABLE IF NOT EXISTS public.yeu_cau_tu_van (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  ho_ten text not null,
  so_dien_thoai text not null,
  noi_dung text,
  trang_thai text default 'Chưa xử lý' -- 'Chưa xử lý', 'Đã liên hệ', 'Đã chuyển hồ sơ'
);

-- 5. Create Matching Table (Ghép đơn - Setup Phỏng vấn)
CREATE TABLE IF NOT EXISTS public.candidate_order (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  candidate_id bigint references public.ho_so(id) on delete cascade not null,
  order_id bigint references public.don_hang(id) on delete cascade not null,
  status text default 'Pending', -- 'Pending', 'Interview', 'Passed', 'Failed'
  notes text,
  interview_date timestamp with time zone,
  
  -- Constraint to prevent duplicate matching
  unique(candidate_id, order_id)
);

-- 6. Create POLICIES (Public Access for Demo)
-- WARNING: In production, you should restrict these policies.

-- ho_so
DROP POLICY IF EXISTS "Enable all access for all users" ON public.ho_so;
CREATE POLICY "Enable all access for all users" ON public.ho_so FOR ALL USING (true) WITH CHECK (true);

-- don_hang
DROP POLICY IF EXISTS "Enable all access for all users" ON public.don_hang;
CREATE POLICY "Enable all access for all users" ON public.don_hang FOR ALL USING (true) WITH CHECK (true);

-- yeu_cau_tu_van
DROP POLICY IF EXISTS "Enable all access for all users" ON public.yeu_cau_tu_van;
CREATE POLICY "Enable all access for all users" ON public.yeu_cau_tu_van FOR ALL USING (true) WITH CHECK (true);

-- candidate_order
DROP POLICY IF EXISTS "Enable all access for all users" ON public.candidate_order;
CREATE POLICY "Enable all access for all users" ON public.candidate_order FOR ALL USING (true) WITH CHECK (true);
