-- Tạo bảng Yêu Cầu Tư Vấn (Leads)
create table if not exists public.yeu_cau_tu_van (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  ho_ten text not null,
  so_dien_thoai text not null,
  tuoi int,
  que_quan text,
  ghi_chu text, -- Lưu tên đơn hàng quan tâm
  trang_thai text default 'Chờ xử lý' -- Chờ xử lý / Đã liên hệ
);

-- Bật RLS
alter table public.yeu_cau_tu_van enable row level security;

-- Policy cho phép ai cũng được gửi yêu cầu (Insert)
create policy "Public Insert Yeu Cau Tu Van" 
on public.yeu_cau_tu_van for insert 
with check (true);

-- Policy cho phép Admin xem (Select) - Tạm thời public để demo
create policy "Public View Yeu Cau Tu Van" 
on public.yeu_cau_tu_van for select 
using (true);
