-- 1. Tạo bảng ho_so nếu chưa có
CREATE TABLE IF NOT EXISTS public.ho_so (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  ho_ten text not null,
  so_dien_thoai text,
  nam_sinh integer,
  que_quan text,
  ghi_chu text,
  trang_thai text default 'Chờ tư vấn',
  nguon text default 'Web'
);

-- 2. Bổ sung các cột vào bảng don_hang (nếu chưa có) sử dụng khối lệnh DO an toàn
DO $$
BEGIN
    -- Thêm cột trang_thai nếu chưa có
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'don_hang' AND column_name = 'trang_thai') THEN
        ALTER TABLE public.don_hang ADD COLUMN trang_thai text DEFAULT 'Đang tuyển';
    END IF;

    -- Thêm cột mo_ta_cong_viec nếu chưa có
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'don_hang' AND column_name = 'mo_ta_cong_viec') THEN
        ALTER TABLE public.don_hang ADD COLUMN mo_ta_cong_viec text;
    END IF;

    -- Thêm cột muc_luong (text) nếu chưa có
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'don_hang' AND column_name = 'muc_luong') THEN
        ALTER TABLE public.don_hang ADD COLUMN muc_luong text;
    END IF;
    
    -- Thêm cột so_luong_tuyen nếu chưa có
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'don_hang' AND column_name = 'so_luong_tuyen') THEN
        ALTER TABLE public.don_hang ADD COLUMN so_luong_tuyen integer DEFAULT 1;
    END IF;
    
    -- Thêm cột thoi_han_nop_ho_so
     IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'don_hang' AND column_name = 'thoi_han_nop_ho_so') THEN
        ALTER TABLE public.don_hang ADD COLUMN thoi_han_nop_ho_so date;
    END IF;
END $$;

-- 3. Cập nhật quyền truy cập (RLS)
ALTER TABLE public.ho_so ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.don_hang ENABLE ROW LEVEL SECURITY;

-- Reset và tạo lại Policy để đảm bảo quyền truy cập Public (cho demo)
DROP POLICY IF EXISTS "Enable all access for all users" ON public.don_hang;
CREATE POLICY "Enable all access for all users" ON public.don_hang FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Enable all access for all users" ON public.ho_so;
CREATE POLICY "Enable all access for all users" ON public.ho_so FOR ALL USING (true) WITH CHECK (true);
