-- 1. Bảng Hồ Sơ (Candidates)
create table if not exists public.ho_so (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Thông tin cá nhân
  ho_ten text not null,
  ngay_sinh date,     -- Dùng date để tính tuổi chính xác
  gioi_tinh text,
  que_quan text,      -- Tỉnh/Thành phố
  so_dien_thoai text,
  cccd text,
  email text,
  anh_ho_so text,     -- URL ảnh
  
  -- Thông tin chi tiết (cho form PDF)
  hon_nhan text,      -- Độc thân / Đã kết hôn
  chieu_cao text,     -- cm
  can_nang text,      -- kg
  nhom_mau text,      
  thi_luc text,       -- Ví dụ: 10/10
  tay_thuan text,     -- Phải / Trái
  
  -- Trình độ & Kỹ năng
  trinh_do_van_hoa text,    -- Cấp 3, Cao đẳng...
  trinh_do_tieng_nhat text, -- N5, N4...
  nganh_nghe_mong_muon text, -- Thay cho chuyen_mon
  kinh_nghiem_lam_viec text, -- JSON hoặc text mô tả
  uu_diem text,
  nhu_oc_diem text,
  so_thich text,
  
  -- Gia đình (Lưu dạng JSON hoặc text nếu đơn giản)
  thong_tin_gia_dinh jsonb, 
  
  -- Trạng thái
  trang_thai text default 'Mới đăng ký' -- Mới đăng ký / Đã trúng tuyển / Đã hủy
);

-- 2. Bảng Đơn Hàng (Orders)
create table if not exists public.don_hang (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  ten_don_hang text not null,
  nganh_nghe text,
  dia_diem_lam_viec text, -- Tỉnh tại Nhật
  xi_nghiep_tiep_nhan text,
  nghiep_doan text,
  
  so_luong_tuyen int,
  so_luong_trung_tuyen int,
  
  ngay_phong_van date,
  ngay_tuyen_du_kien date,
  ngay_nhap_canh_du_kien date,
  
  muc_luong text,      -- Ví dụ: 15 man
  chi_phi text,
  yeu_cau_khac text,
  
  trang_thai text default 'Đang tuyển' -- Đang tuyển / Đã chốt / Hoàn thành
);

-- 3. Bảng Liên Kết (Matching Orders & Candidates)
create table if not exists public.lien_ket_don_hang_ho_so (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  don_hang_id bigint references public.don_hang(id) on delete cascade,
  ho_so_id bigint references public.ho_so(id) on delete cascade,
  
  sbd text,           -- Số báo danh (001, 002...)
  ket_qua text default 'Chờ thi', -- Chờ thi / Đỗ / Trượt / Dự bị
  ghi_chu text,
  
  -- Đảm bảo mỗi ứng viên chỉ được add vào một đơn hàng một lần
  constraint unique_candidate_order unique (don_hang_id, ho_so_id)
);

-- 4. Bật Row Level Security (RLS) - Tùy chọn, để mặc định public có thể đọc ghi cho dễ dev
alter table public.ho_so enable row level security;
alter table public.don_hang enable row level security;
alter table public.lien_ket_don_hang_ho_so enable row level security;

-- Policy (Mở toàn quyền cho anon/authenticated để chạy demo, thực tế nên siết chặt)
create policy "Public Access Ho So" on public.ho_so for all using (true) with check (true);
create policy "Public Access Don Hang" on public.don_hang for all using (true) with check (true);
create policy "Public Access Lien Ket" on public.lien_ket_don_hang_ho_so for all using (true) with check (true);
