-- Copy đoạn SQL này và chạy trong Supabase SQL Editor để tạo bảng cần thiết

-- 1. Tạo bảng liên kết giữa Đơn hàng và Hồ sơ
create table if not exists lien_ket_don_hang_ho_so (
  id bigint generated by default as identity primary key,
  don_hang_id bigint references don_hang(id) on delete cascade,
  ho_so_id bigint references ho_so(id) on delete cascade,
  sbd text, -- Số báo danh (001, 002...)
  ghi_chu text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  
  -- Ràng buộc: Một ứng viên chỉ tham gia 1 đơn hàng tại 1 thời điểm (tùy chọn, ở đây để unique cặp đơn-hồ sơ)
  unique(don_hang_id, ho_so_id)
);

-- 2. (Optional) Tạo index để query nhanh hơn
create index if not exists idx_lien_ket_don_hang_id on lien_ket_don_hang_ho_so(don_hang_id);
create index if not exists idx_lien_ket_ho_so_id on lien_ket_don_hang_ho_so(ho_so_id);

-- 3. Policy (Nếu có RLS - Row Level Security, hiện tại đang tắt hoặc public thì không cần)
-- alter table lien_ket_don_hang_ho_so enable row level security;
-- create policy "Enable read access for all users" on lien_ket_don_hang_ho_so for select using (true);
-- create policy "Enable insert for all users" on lien_ket_don_hang_ho_so for insert with check (true);
-- create policy "Enable update for all users" on lien_ket_don_hang_ho_so for update using (true);
-- create policy "Enable delete for all users" on lien_ket_don_hang_ho_so for delete using (true);
